import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import { lato } from "@/assets/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Header />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
